import React from "react";
import "@/app/globals.css";
import Navbar from "../../components/food/generator/navbar";
import { FoodModal} from "../../components/food/generator/FoodModal";
import { FoodDetailContextProvider } from "@/app/context/foodDetailContextProvider";
import { AuthentificationContextProvider } from "@/app/context/AuthentificationContextProvider";
import IsAuthentificated from "@/app/components/authentification/isAuthentificated";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthentificationContextProvider>
      <IsAuthentificated>
        <Navbar />
        <FoodDetailContextProvider>
          <FoodModal />
          {children}
        </FoodDetailContextProvider>
      </IsAuthentificated>
    </AuthentificationContextProvider>
  );
}
